name: CI/CD Build Pipeline # The name of the workflow

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: "Build Application"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: "Build Server"
        if: contains(github.event.pull_request.labels.*.name, 'backend')
        uses: docker/build-push-action@v4
        with:
          context: ./server
          target: production
          secrets: |
            MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}
            MONGO_DB_AUTH_USERNAME=${{ secrets.MONGO_DB_AUTH_USERNAME }}
            MONGO_DB_AUTH_PASSWORD=${{ secrets.MONGO_DB_AUTH_PASSWORD }}
            MONGO_DB_URI=mongodb://mongo:27017
          push: true
          tags: |
            ghcr.io/dmytro-komlyk/prod-nu3on-server:latest

      - name: "Build Client"
        if: contains(github.event.pull_request.labels.*.name, 'frontend-client')
        uses: docker/build-push-action@v4
        with:
          context: ./client
          target: production
          push: true
          tags: |
            ghcr.io/dmytro-komlyk/prod-nu3on-client:latest

      - name: "Build Admin"
        if: contains(github.event.pull_request.labels.*.name, 'frontend-admin')
        uses: docker/build-push-action@v4
        with:
          context: ./admin
          target: production
          push: true
          tags: |
            ghcr.io/dmytro-komlyk/prod-nu3on-admin:latest